### ISSUE TITLE
proxy leecher error formating

### ISSUE THREAD

**Issue by gmalets** [Bardiafa/Proxy-Leecher#2]
Sometimes in proxy list two ip:port elements combined on one string
Could you please review code to fix it?

For example: 

81.19.232.119:80
78.28.152.111:80117.54.114.97:80
203.142.69.251:8080

or 

3.76.14.148:3128
223.247.47.169:8089135.181.82.250:8080
46.40.192.136:8080

**Comment by Bardiafa** [comment]
Hi , Thanks for reporting!

We will fix this bug soon!

**Comment by Bardiafa** [comment]
Hi
 again the bug has been patched
